import type { CV } from './types';

export default <CV>{
  basics: {
    greet: 'Hallo, ich bin',
    firstname: 'Thomas',
    name: 'Lallinger',
    label: 'Fullstack Developer',
    location: 'München, DE',
    image: '/avatar.png',
    email: 'hello@world-wide.dev',
    summary:
      'Ich bin Softwareentwickler mit einer Leidenschaft für Webtechnologien. Ich habe Erfahrung in der Frontend- und Backend-Entwicklung und bin stets motiviert, Neues zu lernen.',
    theme: 'green',
    profiles: [
      {
        network: 'LinkedIn',
        icon: 'mdi:linkedin',
        username: 'Thomas Lallinger',
        url: 'https://www.linkedin.com/in/thomas-lallinger-b3a116117/',
      },
      {
        network: 'GitHub',
        icon: 'mdi:github',
        username: 'tlallinger',
        url: 'https://github.com/tlallinger',
      },
    ],
  },
  work: [
    {
      name: 'Netfonds AG',
      position: 'Fullstack Entwickler',
      location_type: 'Remote',
      location: 'Hamburg, DE',
      url: 'https://www.netfonds.de/',
      startDate: '2021-02-01',
      endDate: null,
      industry: 'Fintech',
      highlights: [],
      responsibilities: [
        'Entwicklung und Wartung von Microservices mit Java und Dropwizard sowie relationalen Datenbankstrukturen.',
        'Erstellung wiederverwendbarer Komponenten zur Sicherstellung von Konsistenz über verschiedene Projekte hinweg.',
        'Mentoring von Junior Entwicklern und neuen Teammitgliedern während des Onboardings, inklusive praktischer Anleitung und kontinuierlicher Unterstützung zur Förderung ihres technischen Wachstums und Integration ins Team.',
        'Durchführung von Code-Reviews mit konstruktivem Feedback und Sicherstellung der Einhaltung von Coding-Standards.',
        'Verantwortlich für Frontend-Tooling und dessen Konfiguration.',
        'Enge Zusammenarbeit mit der IT-Sicherheit zur Identifikation, Bewertung und schnellen Behebung von Code-Schwachstellen mit SonarQube; proaktive Verbesserung der Sicherheitspraktiken durch Entwicklung eigener ESLint-Regeln.',
      ],
      achievements: [
        'Entwicklung und Implementierung einer Microfrontend-Architektur mit Lerna zur Verbesserung der Modularität und Skalierbarkeit, wodurch die gleichzeitige Nutzung verschiedener Frameworks und Versionen ermöglicht wurde.',
        'Erfolgreiche Leitung der Integration neuer Technologien und großer Refactorings, was zu einer Reduzierung der Build-Zeit um mehr als 30% sowie einer gesteigerten Entwicklererfahrung und Produktivität führte.',
      ],
      skills: {
        TypeScript: 'simple-icons:typescript',
        VueJs: 'simple-icons:vuedotjs',
        Tailwind: 'simple-icons:tailwindcss',
        JavaScript: 'simple-icons:javascript',
        Vite: 'simple-icons:vite',
        Lerna: 'simple-icons:lerna',
        vuetify: 'simple-icons:vuetify',
        Node: 'simple-icons:nodedotjs',
        SQL: 'simple-icons:mysql',
        Java: 'mdi:language-java',
        GitHub: 'simple-icons:github',
        Git: 'simple-icons:git',
        Jira: 'simple-icons:jira',
      },
    },
  ],
  skills: [
    {
      name: 'HTML',
      icon: 'simple-icons:html5',
      level: 'Fortgeschritten',
      keywords: ['Webentwicklung', 'Frontend'],
    },
    {
      name: 'CSS',
      icon: 'ri:css3-fill',
      level: 'Fortgeschritten',
      keywords: ['Webentwicklung', 'Frontend', 'Responsives Design'],
    },
    {
      name: 'JavaScript',
      icon: 'simple-icons:javascript',
      level: 'Experte',
      keywords: ['Webentwicklung', 'Frontend', 'Backend', 'Fullstack'],
    },
    {
      name: 'Tailwind',
      icon: 'mdi:tailwind',
      level: 'Fortgeschritten',
      keywords: [
        'Webentwicklung',
        'Frontend',
        'CSS-Framework',
        'Responsives Design',
      ],
    },
    {
      name: 'TypeScript',
      icon: 'simple-icons:typescript',
      level: 'Experte',
      keywords: [
        'Webentwicklung',
        'Frontend',
        'Backend',
        'JavaScript-Erweiterung',
      ],
    },
    {
      name: 'Node',
      icon: 'ri:nodejs-line',
      level: 'Fortgeschritten',
      keywords: ['Webentwicklung', 'Backend', 'JavaScript', 'Server'],
    },
    {
      name: 'SQL',
      icon: 'simple-icons:mysql',
      level: 'Fortgeschritten',
      keywords: ['Datenbanken', 'SQL', 'Datenspeicherung', 'Backend'],
    },
    {
      name: 'MongoDB',
      icon: 'simple-icons:mongodb',
      level: 'Anfänger',
      keywords: ['Datenbanken', 'Datei', 'Datenspeicherung', 'Backend'],
    },
    {
      name: 'Git',
      icon: 'mdi:git',
      level: 'Fortgeschritten',
      keywords: ['Versionskontrolle', 'Zusammenarbeit', 'Quellcode'],
    },
    {
      name: 'GitHub',
      icon: 'mdi:github',
      level: 'Experte',
      keywords: ['Versionskontrolle', 'Zusammenarbeit', 'Quellcode', 'Git'],
    },
    {
      name: 'React',
      icon: 'mdi:react',
      level: 'Fortgeschritten',
      keywords: ['Webentwicklung', 'Frontend', 'JavaScript-Bibliothek', 'UI'],
    },
    {
      name: 'Vue',
      icon: 'mdi:vuejs',
      level: 'Experte',
      keywords: ['Webentwicklung', 'Frontend', 'JavaScript-Bibliothek', 'UI'],
    },
    {
      name: 'Vite',
      icon: 'simple-icons:vite',
      level: 'Fortgeschritten',
      keywords: ['Webentwicklung', 'Frontend', 'Build-Tool'],
    },
    {
      name: 'WordPress',
      icon: 'ri:wordpress-fill',
      level: 'Fortgeschritten',
      keywords: ['PHP', 'Fullstack', 'Frontend'],
    },
    {
      name: 'Golang',
      icon: 'simple-icons:go',
      level: 'Anfänger',
      keywords: ['Backend', 'Cloud-Service'],
    },
    {
      name: 'Astro',
      icon: 'simple-icons:astro',
      level: 'Fortgeschritten',
      keywords: ['Webentwicklung', 'Frontend', 'SSR', 'Statische Generierung'],
    },
    {
      name: 'Sass',
      icon: 'simple-icons:sass',
      level: 'Fortgeschritten',
      keywords: ['Webentwicklung', 'Frontend', 'CSS-Präprozessor'],
    },
    {
      name: 'Vuetify',
      icon: 'simple-icons:vuetify',
      level: 'Fortgeschritten',
      keywords: ['Webentwicklung', 'Frontend', 'UI-Framework'],
    },
    {
      name: 'Lerna',
      icon: 'simple-icons:lerna',
      level: 'Fortgeschritten',
      keywords: ['JavaScript', 'Monorepo'],
    },
    {
      name: 'Jira',
      icon: 'simple-icons:jira',
      level: 'Fortgeschritten',
      keywords: ['Projektmanagement'],
    },
    {
      name: 'Netlify',
      icon: 'simple-icons:netlify',
      level: 'Fortgeschritten',
      keywords: ['Serverlos', 'Statisches Hosting'],
    },
  ],
  languages: [
    {
      language: 'Deutsch',
      fluency: 'Muttersprache',
    },
    {
      language: 'Englisch',
      fluency: 'Fließend',
    },
  ],
};
